# Default values for benchmarking.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: "vanvalenlab/kiosk-benchmarking"
  tag: "latest"
  pullPolicy: "Always"

resources: {}

env:
  BENCHMARKING_PU_TYPE_AND_NUMBER: "specify_me"
  BENCHMARKING_PU_TYPE: "specify_me"
  IMG_NUM: 0
  BENCHMARK_MODEL: "specify_me"
  BENCHMARK_MODEL_VERSION: "specify_me"
  BENCHMARK_POSTPROCESSING: "specify_me"
  BENCHMARK_CUTS: 0
  GPU_TYPE: "specify_me"
  UPLOAD_METHOD: "specify_me"
  IMAGES_PER_ZIP: 0
  BUCKET: "specify_me"
  BUCKET_FOLDER: "specify_me"
