apiVersion: v1
name: redis-consumer
version: 0.5.0
#kubeVersion: ^1.9.8
description: This project consumes and processes redis event, placing the final result back to redis.
keywords:
  - kiosk-redis-consumer
home: https://www.github.com/vanvalenlab/kiosk-redis-consumer
sources:
  - https://hub.docker.com/vanvalenlab/kiosk-redis-consumer
maintainers:
  - name: Dylan Bannon
    email: bbannon@caltech.edu
    url: vanvalen.caltech.edu
engine: gotpl
appVersion: 0.11.0
deprecated: false
tillerVersion: ^2.9.1
