apiVersion: v1
name: tf-serving
version: 0.4.0
#kubeVersion: ^1.9.8
description: This helm chart provides the Tensorflow-serving backend functionality of the Deepcell application.
keywords:
  - tensorflow-serving
home: https://www.github.com/vanvalenlab/kiosk-tf-serving
sources:
    - https://hub.docker.com/vanvalenlab/kiosk-tf-serving
maintainers:
  - name: Dylan Bannon
    email: bbannon@caltech.edu
    url: vanvalen.caltech.edu
engine: gotpl
appVersion: 0.4.0
deprecated: false
tillerVersion: ^2.9.1

